### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by igogo5yo** [kiriapurv/node-camera#2]
```
Ihors-MacBook-Pro:node-camera ihor$ npm start

> Streaming@ start /Users/ihor/www/node-camera
> node src/main.js


module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/ihor/www/node-camera/build/Release/camera.node, 1): Symbol not found: _OBJC_CLASS_$_NSApplication
  Referenced from: /Users/ihor/www/node-camera/build/Release/camera.node
  Expected in: dynamic lookup

    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ihor/www/node-camera/src/main.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! Streaming@ start: `node src/main.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Streaming@ start script.
npm ERR! This is most likely a problem with the Streaming package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Streaming
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/ihor/.nvm/v0.10.39/bin/node" "/Users/ihor/.nvm/v0.10.39/bin/npm" "start"
npm ERR! cwd /Users/ihor/www/node-camera
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ihor/www/node-camera/npm-debug.log
npm ERR! not ok code 0
```

**Comment by kiriapurv** [comment]
Did `npm install` successfully build native addon ?

**Comment by igogo5yo** [comment]
Yes! And node-gyp rebuild successfully too!
But node-gyp rebuild is success only with node v0.10 
On node v0.12 I have node-gyp rebuild error :(

**Comment by igogo5yo** [comment]
Full npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ihor/.nvm/v0.10.39/bin/node',
1 verbose cli   '/Users/ihor/.nvm/v0.10.39/bin/npm',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.39
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Streaming@
6 info start Streaming@
7 verbose unsafe-perm in lifecycle true
8 info Streaming@ Failed to exec start script
9 error Streaming@ start: `node src/main.js`
9 error Exit status 8
10 error Failed at the Streaming@ start script.
10 error This is most likely a problem with the Streaming package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node src/main.js
10 error You can get their info via:
10 error     npm owner ls Streaming
10 error There is likely additional logging output above.
11 error System Darwin 15.0.0
12 error command "/Users/ihor/.nvm/v0.10.39/bin/node" "/Users/ihor/.nvm/v0.10.39/bin/npm" "start"
13 error cwd /Users/ihor/www/node-camera
14 error node -v v0.10.39
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```

**Comment by kiriapurv** [comment]
### For v0.10 
Check where the native module is placed after build, whether its in `build/Release/camera.node` or `build/Debug/camera.node`. Change path accordingly in [main.js#L2](https://github.com/kiriapurv/node-camera/blob/master/src/main.js#L2)

### For newer node versions 
Check issue #1

**Comment by igogo5yo** [comment]
## For v0.10 
Path is ok, but I have same error

## For newer (I checkout iojs brunch)
I have same error with ```npm start``` but with ```node-gyp rebuild``` I have these warnings: 
```
Ihors-MacBook-Pro:node-camera ihor$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.1
gyp info using node@0.12.5 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ihor/www/node-camera/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ihor/.node-gyp/0.12.5/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ihor/.node-gyp/0.12.5',
gyp info spawn args   '-Dmodule_root_dir=/Users/ihor/www/node-camera',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
2015-07-03 17:48:26.669 xcodebuild[10938:173578] [MT] PluginLoading: Required plug-in compatibility UUID AABB7188-E14E-4433-AD3B-5CD791EAD9A3 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/camera/src/native/camera.o
  SOLINK_MODULE(target) Release/camera.node
ld: warning: object file (Release/obj.target/camera/src/native/camera.o) was built for newer OSX version (10.7) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_highgui.a(window.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(imgwarp.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(alloc.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_highgui.a(window_cocoa.mm.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(convert.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(parallel.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(copy.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(system.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(ocl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opencl_kernels_core.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_imgproc.a(opencl_kernels_imgproc.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(opengl.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(stat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(umatrix.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_gpu_mat.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_stream.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(cuda_host_mem.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(lapack.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(kmeans.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(array.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matop.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(mathfuncs.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(datastructs.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(arithm.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(tables.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(matmul.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(rand.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(persistence.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
ld: warning: object file (/usr/local/lib/libopencv_core.a(pca.cpp.o)) was built for newer OSX version (10.11) than being linked (10.5)
gyp info ok 
```

**Comment by kiriapurv** [comment]
Rebuild opencv. See if problem persists after warnings are gone.

**Comment by igogo5yo** [comment]
Thanks!
I reinstall opencv and on node v0.10 I take video :)
